export default {
  LOAD_APPLICATIONS: 'LOAD_APPLICATIONS',
  APPLICATIONS_LOADED: 'APPLICATIONS_LOADED',

  LOAD_PERMISSIONS: 'LOAD_PERMISSIONS',
  PERMISSIONS_LOADED: 'PERMISSIONS_LOADED',
  SAVE_PERMISSION: 'SAVE_PERMISSION',
  PERMISSION_SAVED: 'PERMISSION_SAVED',
  DELETE_PERMISSION: 'DELETE_PERMISSION',
  PERMISSION_DELETED: 'PERMISSION_DELETED',
  
  LOAD_ROLES: 'LOAD_ROLES',
  ROLES_LOADED: 'ROLES_LOADED',
  SAVE_ROLE: 'SAVE_ROLE',
  ROLE_SAVED: 'ROLE_SAVED',
  DELETE_ROLE: 'DELETE_ROLE',
  ROLE_DELETED: 'ROLE_DELETED',

  ADD_ROLE_PERMISSIONS: 'ADD_ROLE_PERMISSIONS',
  DELETE_ROLE_PERMISSION: 'DELETE_ROLE_PERMISSION',
  ADD_ROLE_SUBROLES: 'ADD_ROLE_SUBROLES',
  DELETE_ROLE_SUBROLE: 'DELETE_ROLE_SUBROLE',

  LOAD_USERS: 'LOAD_USERS',
  USERS_LOADED: 'USERS_LOADED',
  ADD_USER_ROLES: 'ADD_USER_ROLES',
  USER_ROLES_ADDED: 'USER_ROLES_ADDED',
  DELETE_USER_ROLES: 'DELETE_USER_ROLES',
  USER_ROLES_DELETED: 'USER_ROLES_DELETED',

  SNACKBAR_SHOW: 'SNACKBAR_SHOW',
  SNACKBAR_HIDE: 'SNACKBAR_HIDE',

  USER_AUTHENTICATING: 'USER_AUTHENTICATING',
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  RECEIVED_PROFILE: 'RECEIVED_PROFILE',
  RECEIVED_APPS: 'RECEIVED_APPS',
  RECEIVED_USERS: 'RECEIVED_USERS',
  PAGE_TITLE_SET: 'PAGE_TITLE_SET',
  RECEIVED_ROLES: 'RECEIVED_ROLES',
  CHECK_AUTHENTICATED: 'CHECK_AUTHENTICATED',
  SAVED_ROLE: 'SAVED_ROLE',
  SAVED_APP: 'SAVED_APP',
  SAVED_USER: 'SAVED_USER',
  DELETED_ROLE: 'DELETED_ROLE',
  SETTINGS_SAVED: 'SETTINGS_SAVED'
}